version: '3'

services: 

  laravel:
    build: 
      context: ./lavarel
      dockerfile: Dockerfile.prod
    image: mathcard/lavarel
    container_name: laravel_compose
    networks: 
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: mathcard/nginx
    container_name: nginx_compose
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge      